# Generated by Django 4.2.21 on 2025-06-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('websocket', 'WebSocket'), ('longpolling', 'Long Polling'), ('push', 'Push Notifications')], max_length=20)),
                ('alert_title', models.CharField(max_length=255)),
                ('alert_message', models.TextField()),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=20)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('client_count', models.IntegerField(default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100, unique=True)),
                ('technology', models.CharField(choices=[('websocket', 'WebSocket'), ('longpolling', 'Long Polling'), ('push', 'Push Notifications')], max_length=20)),
                ('test_config', models.JSONField()),
                ('metrics', models.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('websocket', 'WebSocket'), ('longpolling', 'Long Polling'), ('push', 'Push Notifications')], max_length=20, unique=True)),
                ('avg_latency_ms', models.FloatField(default=0)),
                ('min_latency_ms', models.FloatField(default=0)),
                ('max_latency_ms', models.FloatField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('max_concurrent_clients', models.IntegerField(default=0)),
                ('messages_per_second', models.FloatField(default=0)),
                ('avg_connection_time_ms', models.FloatField(default=0)),
                ('total_data_transferred_bytes', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Technology Metrics',
                'ordering': ['technology'],
            },
        ),
    ]
