# Generated by Django 4.2.21 on 2025-06-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=255)),
                ('alert_message', models.TextField()),
                ('alert_type', models.CharField(default='push', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
