# Generated by Django 5.2.3 on 2025-06-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_enhanced_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertdeliverylog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Alert Delivery Log', 'verbose_name_plural': 'Alert Delivery Logs'},
        ),
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'FCM Token', 'verbose_name_plural': 'FCM Tokens'},
        ),
        migrations.AlterModelOptions(
            name='performancetestresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Performance Test Result', 'verbose_name_plural': 'Performance Test Results'},
        ),
        migrations.AlterModelOptions(
            name='technologymetrics',
            options={'ordering': ['technology'], 'verbose_name': 'Technology Metrics', 'verbose_name_plural': 'Technology Metrics'},
        ),
    ]
